export { string as me } from './me.gql'
export { string as getDraft } from './getDraft.gql'
export { string as getText } from './getText.gql'
export { string as getProfile } from './getProfile.gql'
export { string as listTexts } from './listTexts.gql'
