schema {
  query: Query
  mutation: Mutation
}

type Query {
  me: Person
}

type Mutation {
  signInGoogle(code: ID!, redirect: String!): Person
  signOut: Int
  createText: Text!
}

type Person {
  id: String!
  name: String!
}

type Text {
  id: String!
}
